# Generated by Django 5.1.2 on 2024-10-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='orderitems',
            table='OrderItems',
        ),
        migrations.AlterModelTable(
            name='paymentdetails',
            table='Payment Details',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='Sub Category',
        ),
    ]
