# Generated by Django 5.1.2 on 2024-10-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='amount',
            field=models.FloatField(editable=False),
        ),
    ]
