# Generated by Django 5.1.2 on 2024-10-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_paymentdetails_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='unpaid', max_length=10),
        ),
    ]
