# Generated by Django 5.1.2 on 2024-11-02 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='name',
        ),
    ]
