# Generated by Django 5.1.2 on 2024-11-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_customuser_token_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default=None, max_length=10),
        ),
    ]
